### ISSUE TITLE
Add 'Dump Scripts' test option via test provider/ingredient

### ISSUE THREAD

**Issue by t1lde** [Liqwid-Labs/plutus-extra#110]
For various workflows, It would be pretty useful to have an option to dump PlutusIR, Plutus Core, and Untyped Plutus Core of scripts involved in `tasty-plutus` tests, including the size tests.

I have a rough mockup which dumps uplc to files when the `--dump-scripts path` option is set, using a test-provider for IO, requiring manual annotation of tests via `withDumpScripts`.

My mockup ([Gist](https://gist.github.com/t1lde/f1becd42c1236a32f608f7e6e289bd3b))

Some additions/changes that could be made:
- It would be nicer to have this built into `WithScript` directly.
- Better options UX
- Dumping PIR and typed PLC - this would require the `CompiledCode` values rather than the `Script` values I'm using here (WithScript would also be convenient here)
- It might be better as a Tasty Ingredient, rather than a test Provider

**Comment by kozross** [comment]
I think a tasty ingredient (probably via the option interface) is the right idea here. I reckon having the ability to dump each one of PlutusIR, Plutus Core and untyped Plutus Core as separate options would be the right idea.

What do you mean by 'better options UX' here @t1lde? Is this an issue with how `tasty` deals with options, or something else?

**Comment by kozross** [comment]
For @re-xyr: I think the right approach for this are `tasty` options. I'm happy to let you drive the design. This would be PRed against `master`, minor bump. Let me know if you hit any trouble: you can use the existing options in `tasty-plutus` as examples.

**Comment by t1lde** [comment]
By 'better options' I meant, maybe it's worth putting more thought into the CLI options vs what's present in the Gist snippet. Probably *fine* as is though

**Comment by re-xyr** [comment]
I have looked into `tasty` ingredients and I think that it is impossible to implement this as an ingredient. This is because an ingredient only gets a `TestTree`, and we cannot inspect the exact type of the tests in the tree; therefore we cannot possibly extract the `Script`s in the tree.

So, there are still two solutions:
- Add the options to both unit tests and property tests; or
- Implement a test provider to wrap over `ScriptTest` and `PropertyTest`.

I think the second one is less likely to have code duplication, so I'm going to experiment with that first.

**Comment by re-xyr** [comment]
For PIR and typed PLC, we can do it this way:

- Instead of requiring users passing in `TypedValidator`s we require a `CompiledCode (datum -> redeemer -> ScriptContext -> Bool)` for validators. This way we have PIR and typed PLC.
- Inside `withValidator`, we call `mkTypedValidator` with `toTestValidator`. This way we have a `TypedValidator s`. Therefore we have `Script`, i.e. untyped PLC.

The types of `withValidator` and `withMintingPolicy` will look like something like this:

```hs
withValidator ::
  forall (s :: Type).
  String ->
  CompiledCode (DatumType s -> RedeemerType s -> ScriptContext -> Bool) ->
  WithScript ( 'ForSpending (DatumType s) (RedeemerType s)) () ->
  TestTree

withMintingPolicy ::
  forall (r :: Type).
  String ->
  CompiledCode (r -> ScriptContext -> Bool) ->
  WithScript ( 'ForMinting r) () ->
  TestTree
```

This will be a breaking change.

**Comment by kozross** [comment]
@re-xyr That monomorphism problem is exactly why I went with the design that I did initially. I don't mind a breaking change if this would make for a better API.
