### ISSUE TITLE
`Natural` functions for Map

### ISSUE THREAD

**Issue by samuelWilliams99** [Liqwid-Labs/plutus-extra#163]
We have a series of helper functions for Lists that work with Naturals over Ints, could we get this for Maps?
The pattern of functions like `Map.take . fromInteger . natToInteger` gets a little cumbersome

**Comment by kozross** [comment]
What kind of `Map`s are these @samuelWilliams99? Plutus ones, or some other kind?

Is there a list of functions you would like?

**Comment by samuelWilliams99** [comment]
`Data.Map` or `PlutusTx.AssociativeMap`, or both.
And I'm thinking functions like
`take`, `drop`, `size`
Nothing too involved

**Comment by blamario** [comment]
Maybe it's better to generalize these functions to work on any `Witherable`, at least off-chain.

https://hackage.haskell.org/package/witherable-0.4.2/docs/Data-Witherable.html#t:Witherable

**Comment by kozross** [comment]
I agree with @blamario for the off-chain part at least. For on-chain with `AssocMap`, I'll come up with a list.

**Comment by re-xyr** [comment]
If the off-chain part is for all `Witherable`s then it may make sense for them to be put in `plutus-list`, but not quite so for `AssocMap`-specialized on-chain code. @kozross do you think we should create another package for it?

**Comment by re-xyr** [comment]
I tried to implement `take` and `drop` for `Witherable`:

```haskell
takeW :: Witherable t => Int -> t a -> t a
takeW n = flip evalState 1 . wither (\x ->
  state $ \s -> (if s > n then Nothing else Just x, succ s))

dropW :: Witherable t => Int -> t a -> t a
dropW n = flip evalState 0 . wither (\x ->
  state $ \s -> (if s < n then Nothing else Just x, succ s))
```

The efficiency will be `O(length)` which is not very desirable. `length` for `Foldable`s are already in `plutus-list`.

**Comment by kozross** [comment]
@re-xyr I think we might want to rename `plutus-list` to `plutus-collection`. That way, we can put all collection-related code in there, regardless of what collection(s) it's usable for or with.

Regarding efficiency for `Witherable`: @blamario and @samuelWilliams99 can have the final call, but I suspect this _should_ use specialized versions for now, since we only need it to generalize to like, two kinds of collection?

**Comment by kozross** [comment]
@re-xyr Sorry this list took a while. I think we need `AssocMap` versions of `take`, `drop` and `splitAt`, since they're the only functions that take numeric arguments related to length. They should also be possible for any `Witherable` for offchain use. Does this meet your criteria @samuelWilliams99?

**Comment by samuelWilliams99** [comment]
Absolutely! Just to clarify, we'll have those functions inlinable specialise for onchain, then just do instances of Witherable for offchain?

**Comment by re-xyr** [comment]
I think off-chain code does not use PlutusTx typeclasses or types, so there isn't much point in defining `take` and `drop` for `Natural`. @kozross what do you think?

**Comment by samuelWilliams99** [comment]
We do use Naturals offchain, for both plutustx types like `AssocMap`, and non plutustx types like simply `Map`

**Comment by kozross** [comment]
@samuelWilliams99 is right - we use values of `plutus-numeric` types off-chain fairly regularly in several projects.
