### ISSUE TITLE
Unsynchronized `tasty-plutus` test error reporting

### ISSUE THREAD

**Issue by maciej-bendkowski** [Liqwid-Labs/plutus-extra#202]
I'm running `tasty-plutus` tests in a _multithreaded_ environment using:
```bash
cabal v2-test --test-options="--num-threads=4" --test-show-details=direct
```
I have a failing property test and a bunch of other, successful tests. When I run the tests I get a test log with the following contents:

```
...
Test Group G:
  Successful test A:         *** Failed! Falsified (after 1 test):
  Inputs:
    ...
  Context:
    ...
  Configuration:
    ...
 Logs
   OK (2.20s)
...
Test Group G':
  Failing test B:              FAIL (0.11s)
 ...
```

Logs being displayed under test A are in fact logs for the failing test B. It seems that the error log reporting is not properly synchronized with the whole test report. I _suspect_ that multiple threads are grabbing tests in parallel and dump log traces _as soon as_ the test can be falsified _without_ synchronizing in which order these should be dumped.

I can confirm that the test logs are fine if multithreading is disabled through `--num-threads=1`. I'm using `plutus-extra` version `847437f6a7bb5825685a7ecf4421c3de8f2c8e36`. I'm not sure if that a `tasty-plutus` bug or if it's a `tasty` bug.

**Comment by kozross** [comment]
I think this is a `tasty` issue - I've seen this happen before with other `tasty-*` packages.

**Comment by re-xyr** [comment]
Strangely, `tasty-quickcheck` doesn't have this problem. Maybe this is actually a problem with `tasty-plutus`?

**Comment by re-xyr** [comment]
I think I found the culprit: `tasty-plutus` directly outputs QuickCheck logs instead of returning them to `tasty` with `testSuccess` and `testFailure`. `tasty` will *run the tests* on multiple threads, but result reporting is on one thread. And result reporting queries (and blocks on) results in a particular order. 

So this situation can happen: 4 property tests are running in worker threads and spitting out QuickCheck logs right away, while the `tasty` result reporter is still blocked on one test (because that test is not finished), and we get horribly out-of-sync test logs. I think this is relatively easy to fix.

**Comment by kozross** [comment]
Good work @re-xyr!
