### ISSUE TITLE
Semimodule type class

### ISSUE THREAD

**Issue by kozross** [Liqwid-Labs/plutus-extra#216]
This is an extension (and in some sense, a superseder) of #213. Unfortunately, due to the design choices inherent in `plutus-tx`, using rewrite rules against it is impossible: we simply have nothing to match on once `compile` happens, and it occurs long before we apply rewrite rules.

Instead, we should define a new type class, `Semimodule`, as follows:

```haskell
class (Semiring s, AdditiveMonoid v) => Semimodule s v | v -> s where
    semiscale :: s -> v -> v
```

With the following laws:

* `semiscale x z + semiscale y z = semiscale (x + y) z`
* `semiscale x (semiscale y z) = semiscale (x * y) z`
* `semiscale zero x = zero`
* `semiscale one x = x`

This is essentially a [mathematical semimodule](https://en.wikipedia.org/wiki/Semimodule), with the difference that we don't demand that it's an additive group. We also note that `semiscale` is a more general version of `scaleNat`.

We would need the following instances, with optimized `semiscale`s:

* `Semimodule Natural Integer`
* `Semimodule Natural Rational`
* `Semimodule Natural NatRatio`
* `Semimodule Natural Value` (although this one is a bit debatable)

As part of this effort, `plutus-laws` needs to be extended with law tests for the laws above, and such tests must be added for all instances. We also need to thoroughly document `Semimodule` in the style of the other type classes.

Lastly, we want benchmarks (similar in style to the ones I added to #215) to show that `semiscale` beats `scaleNat` in performance and code size. Then, we need to add a DEPRECATED pragma to `scaleNat`, advising people to instead use `semiscale`.

**Comment by re-xyr** [comment]
I'm a bit unsure about making this an MPTC. There is nothing inherent about `v` determining `s` - it's not in the mathematical definition. If we're to define `semiscale` over other types it'd be impossible too.

Rather, maybe we can fix `s` to be `Natural` and call this class `NatModule` or something like that. i.e.,

```haskell
class (AdditiveMonoid v) => NatModule v where
    scaleNat :: Natural -> v -> v
```

**Comment by kozross** [comment]
We could do that, but I honestly don't feel that a fundep is such a problem. The main reason we have a fundep is to not break inference, and if we _really_ need to `semiscale` by several types, you can always use a `newtype`. This also mirrors how `Module` from `PlutusTx.Numeric` works.

**Comment by kozross** [comment]
We already have [`Semiring`](https://playground.plutus.iohkdev.io/doc/haddock/plutus-tx/html/PlutusTx-Numeric.html#t:Semiring).

**Comment by blamario** [comment]
Apologies. I expected `Semiring` to be a type class and I didn't see it in the list of `NatRatio` instances, so I assumed it would be a new thing. I also have to walk back the `instance Semimodule NatRatio` idea, because there would be three alternative implementations depending on whether one wants to apply `truncate`, `ceiling`, or `round` after the multiplication. So we'd need three newtypes like `TruncatedModuleNatRatio` etc instead. The interface / implementation code size ratio would be too high.

I still maintain that the scaling of `Value` by an integer amount is a practically useless operation, regardless of which typeclass it's attached to. It would be more useful to have an [instance MonoFunctor Value](https://hackage.haskell.org/package/mono-traversable-1.0.15.3/docs/Data-MonoTraversable.html#t:MonoFunctor), except I'm not sure there would be any other useful instances of Plutus data types.

**Comment by kozross** [comment]
Why would you need to `truncate` or anything else? `instance Semimodule Natural NatRatio` would just scale a `NatRatio` by multiplying by a `Natural`. This fits all the laws.

**Comment by blamario** [comment]
I was talking about `instance Semimodule NatRatio Value`; it would have to choose one of the three ways to convert from `NatRatio` to `Natural`.
